### ISSUE TITLE
Multi Word Directory Names

### ISSUE THREAD

**Issue by Jake-Day-Williams** [eatspaint/pkdir#1]
Two directories are created when attempting to create directories with multi word names. See screenshot below. 
<img width="623" alt="screen shot 2016-06-28 at 4 44 16 pm" src="https://cloud.githubusercontent.com/assets/17089983/16434896/aecae8d8-3d4f-11e6-8733-4bc1b864eb5c.png">

**Comment by eatspaint** [comment]
Added wrapping single quotes around ARGV[0], should now accept escaped spaces as well as quoted spaced names. 
See commit: 4f77f10
