### ISSUE TITLE
Add/Check Linux support

### ISSUE THREAD

**Issue by ClikeX** [eatspaint/pkdir#3]
It would be nice to add or ensure it works for Linux as well. And add instructions for it in the readme.

**Comment by eatspaint** [comment]
The readme currently states that the script is OSX only. As the script relies on [fileicon](https://github.com/mklement0/fileicon) -  an OSX CLI, it currently will not work for Linux. I would be open to a PR from someone who wants to build Linux support.

**Comment by eatspaint** [comment]
@ClikeX would you like to check this out for Linux? I've got my hands pretty full with work right now so I don't have much time to mess with a VM at the moment.

**Comment by ClikeX** [comment]
@eatspaint Yeah, I kinda made the issue to remind me of it. Or for someone else who wants to tackle it.

I'll check it out this weekend. Can't promise anything, though.

**Comment by ClikeX** [comment]
I'm going to clean up this ticket since I'm obviously not going to implement this anymore at this point.
